package com.ecommerceWishlist.ecommerceWishlist.model.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "wishlist")
public class Wishlist {
    @DynamoDBHashKey(attributeName = "wishlistId")
    @DynamoDBAutoGeneratedKey
    private String wishlistId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String userId;

    @DynamoDBAttribute
    private List<String> products;

}
